language: c

# ------------------------------------------------------------------------------
# Compilation matrix
#
# It is used to build MCUSim on the different operating systems with different
# set of dependencies and options.
# ------------------------------------------------------------------------------
matrix:
  include:

# ------------------
# GNU/Linux with GCC
# ------------------
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libluajit-5.1-2
            - libluajit-5.1-dev
        sonarcloud:
          organization: "mcusim"
        cache:
          directories:
            - '$HOME/.sonar/cache'
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      # Build phases are defined according to their order in Travis CI.
      before_install:
        - eval "${MATRIX_EVAL}"
      before_script:
        - cmake ${CMAKE_PARAMS} .
      script:
        - make clean
        # Wraps the compilation with the Build Wrapper to generate configuration
        # (used later by the SonarQube Scanner) into the "bw-output" folder.
        - build-wrapper-linux-x86-64 --out-dir bw-output make
        # And finally run the SonarQube analysis - read the
        # "sonar-project.properties" file to see the specific configuration
        - sonar-scanner

# --------------------
# GNU/Linux with Clang
# --------------------
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libluajit-5.1-2
            - libluajit-5.1-dev
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
      # Build phases are defined according to their order in Travis CI.
      before_install:
        - eval "${MATRIX_EVAL}"
      before_script:
        - mkdir build && cd build
        - cmake ${CMAKE_PARAMS} ..
      script:
        - make clean
        - make
        - make tests

# ----------------
# macOS with Clang
# ----------------
#    - os: osx
#      osx_image: xcode10.1
#      env:
#        - MATRIX_EVAL="brew install luajit"


# --------------------------------
# GNU/Linux with XSPICE code model
# --------------------------------
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-7
#            - libluajit-5.1-2
#            - libluajit-5.1-dev
#            - libreadline6
#            - libreadline6-dev
#            - bison
#            - flex
#            - libx11-6
#            - libx11-dev
#            - libxau6
#            - libxau-dev
#            - libxext6
#            - libxext-dev
#            - libxinerama1
#            - libxinerama-dev
#            - libxaw7
#            - libxaw7-dbg
#      env:
#        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
#        - CMAKE_PARAMS="-DWITH_XSPICE=True"


# -------------------------------------------
# GNU/Linux with liblua and XSPICE code model
# -------------------------------------------
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-7
#            - liblua5.2-0
#            - liblua5.2-dev
#            - libreadline6
#            - libreadline6-dev
#            - bison
#            - flex
#            - libx11-6
#            - libx11-dev
#            - libxau6
#            - libxau-dev
#            - libxext6
#            - libxext-dev
#            - libxinerama1
#            - libxinerama-dev
#            - libxaw7
#            - libxaw7-dbg
#      env:
#        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
#        - CMAKE_PARAMS="-DWITH_LUA=True -DWITH_XSPICE=True"


notifications:
  email:
    recipients:
      - dsl@mcusim.org
    on_success: never
    on_failure: always
